# This is a basic workflow to help you get started with Actions

name: Integration-Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
    - ms/**
    - gb/**
    - jl/**
    - mx/**
    - ja/**
  pull_request:
    branches: 
    - dev
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Start Containers
        run: docker-compose -f "./ksqljs/docker-compose.yml" up -d --build
      
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install --prefix "./ksqljs"

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Run tests
        run: npm run test --prefix "./ksqljs"

      - name: Stop containers
        if: always()
        run: docker-compose -f "./ksqljs/docker-compose.yml" down
